baseURL: https://briansunter.com/
languageCode: en-us
title: Brian Sunter
theme: "PaperMod"
timeout: 60s
markup:
  goldmark:
    renderer:
      unsafe: true

params:
    homeInfoParams:
        Title: Welcome to My Personal Site 👋
        Content: Software Engineer based out of San Francisco experienced in web, mobile, and devops. 

    socialIcons: # optional
        - name: "twitter"
          url: "https://twitter.com/bsunter"
        - name: "github"
          url: "https://github.com/briansunter"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/briansunter/"
        - name: "youtube"
          url: "https://www.youtube.com/channel/UC4Nu4dncIcTC1DyOG5XG2Vg"
        - name: "rss"
          url: "https://briansunter.com/index.xml"
        - name: "kofi" 
          url: "https://buymeacoffee.com/bsunter"
        # - name: "bitcoin"
        #   url: "bc1qxnf3v8e9jfavfuyp2f70z03h7ncq8ju7efv3jm"
        - name: "email"
          url: #
        - name: "instagram"
          url: "https://www.instagram.com/bsunter/"
        - name: "matrix"
          url: "https://matrix.to/#/@bsunter:matrix.org"
        # - name: "goodreads"
        #   url: "https://www.goodreads.com/user/show/16975785-brian-sunter"
        # - name: "ycombinator"
        #   url: "https://news.ycombinator.com/user?id=bribri"
        # - name: "kaggle"
        #   url: "https://www.kaggle.com/bsunter"
    ShowReadingTime: true
    author: "Brian Sunter"
    ShowCodeCopyButtons: true
    ShowShareButtons: true
    SiteLogo: /images/sitelogo.jpg
    NewsletterLink: 'https://newsletter.briansunter.com'



outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
    main:
        - identifier: newsletter-link
          name: Newsletter
          url: /newsletter
          weight: 10
        - identifier: topics
          name: Topics
          url: /categories
          weight: 20
        - identifier: tags
          name: Tags
          url: /tags
          weight: 30
        - identifier: archive
          name: Archive
          url: /archives
          weight: 40
        - identifier: graph
          name: Graph
          url: 'https://briansunter.com/graph/#/graph'
          weight: 50
        - identifier: search
          name: Search
          url: /search
          weight: 60